### ISSUE TITLE
楼主，这个是什么问题

### ISSUE THREAD

**Issue by lsh1023** [simolus3/fluttie#17]
Failed to allocate (3240 x 3240) layerCount 1 format 1 usage 133: 5

**Comment by simolus3** [comment]
I'm not sure if I understand your question correctly, but I guess you ran into out of memory errors because the animation you're showing is too big.

You can reduce the size by using the `preferredSize` parameter on the `prepareAnimation` method to make the animation smaller. My suggestion is to use `Size.square(320)` as value. You can increase that value if you want a higher quality , but that will also increase memory usage.

Let me know if that doesn't fix the problem or you're running into other issues.
